### ISSUE TITLE
Taks issue

### ISSUE THREAD

**Issue by netbull** [dobrin08/todo-app-react-semanticui#2]
- multiple similar tasks
- empty tasks

<img width="786" alt="Screenshot 2020-01-16 at 21 24 50" src="https://user-images.githubusercontent.com/2797954/72556208-cfc8ee80-38a6-11ea-994c-7523a045f273.png">

**Comment by dobrin08** [comment]
Improvement on displaying error when user trying to add existing task
Disabled opportunity to add empty task

**Comment by netbull** [comment]
Not really :)

<img width="818" alt="Screenshot 2020-01-17 at 16 12 34" src="https://user-images.githubusercontent.com/2797954/72618654-40721880-3944-11ea-856d-a20877240479.png">

**Comment by dobrin08** [comment]
Fixed

**Comment by netbull** [comment]
Can the solution be improved?
