### ISSUE TITLE
Why `map` is used?

### ISSUE THREAD

**Issue by netbull** [dobrin08/todo-app-react-semanticui#5]
Why `map` is used?

Can the check be optimized?

https://github.com/dobrin08/todo-app-react-semanticui/blob/deaf3b04842a8f143cd2d5b092390b5f90536214/src/App.js#L32

**Comment by dobrin08** [comment]
After looking for the difference between map and forEach I think that .forEach() will be more suitable, because I only iterate over the array, without transform items.

**Comment by netbull** [comment]
Bonus points for the answer, but can you optimize the iteration?

**Comment by dobrin08** [comment]
Optimization that i am thinkink is to not iterate all items in the array - on the first match(if exist) returning true is enought. Thats why i change map() with some().

**Comment by netbull** [comment]
the solution does not work as expected :)
